[project]
name = "scp-zip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "libzim>=3.7.0",
    "lxml>=6.0.0",
]
